-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 21:27:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema byloja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema byloja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `byloja` DEFAULT CHARACTER SET utf8 ;
USE `byloja` ;

-- -----------------------------------------------------
-- Table `byloja`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`produto` (
  `idproduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(45) NOT NULL DEFAULT '/padroes/sem_imagem.png',
  `valor` FLOAT NOT NULL,
  `produtocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`venda_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`venda_cliente` (
  `idvenda_cliente` INT NOT NULL,
  `idcliente` INT NULL,
  PRIMARY KEY (`idvenda_cliente`),
  INDEX `idcliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `idcliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `byloja`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`venda_produto` (
  `idvenda_produto` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idvenda_produto`, `id_produto`),
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `id_venda`
    FOREIGN KEY (`idvenda_produto`)
    REFERENCES `byloja`.`venda_cliente` (`idvenda_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `byloja`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
